name: Check status

on:
  push:
    branches: [main]
  schedule:
    - cron: "*/5 * * * *" # every 5 mins

concurrency:
  group: ${{ github.workflow }}

jobs:
  check:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write # for GitHub pages

    steps:
      - name: Checkout check program
        uses: actions/checkout@v4

      - name: Checkout status
        uses: actions/checkout@v4
        with:
          ref: status
          path: status

      - name: Cache Build Outputs
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: dtolnay/rust-toolchain@stable

      - name: Run status check script
        run: cargo run --release > status/status.json

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: status
          file_pattern: status.json
          commit_message: "Update status"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: status

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
